language: python
sudo: false
python:
- '3.6'
- '3.7'
- '3.8'
services:
  - xvfb # https://benlimmer.com/2019/01/14/travis-ci-xvfb/

before_script:
- "export DISPLAY=:99.0"  # https://docs.travis-ci.com/user/gui-and-headless-browsers
- sleep 3

install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n testenv python=$TRAVIS_PYTHON_VERSION pip pytest numpy pandas
  scipy matplotlib scikit-learn
- source activate testenv
- pip install --upgrade python-coveralls pytest-cov codecov
- pip install -r requirements.txt --upgrade
- pip install -r optional-dependencies.txt --upgrade
- python setup.py install
- cp nltools/tests/matplotlibrc .

script: 
- coverage run --source nltools -m py.test

after_success:
- coveralls
- codecov